### ISSUE TITLE
`assistand_id` — typo for `assistant_id`? or OK?

### ISSUE THREAD

**Issue by TallTed** [OpenLinkSoftware/llama-index-llms-opal#1]
@kidehen @smalinin 

https://github.com/OpenLinkSoftware/llama-index-llms-opal/blob/51e34484ca85117ac0e43821b4d316f2810551be/examples/ex_assistant_2.ipynb#L124-L126

This caught my eye during a session. Searching under the OpenLinkSoftware user, it only occurs in these two lines of this one document, so it seemed likely to be a typo.

Please confirm, in which case I can make the PR, or deny, in which case this issue can simply be closed.

**Comment by smalinin** [comment]
Fixed in https://github.com/OpenLinkSoftware/llama-index-llms-opal/commit/efbc9f2ea16e196388966028df278e1e09a3610f.
